### ISSUE TITLE
ModuleNotFoundError: No module named 'async_extensions.collect'

### ISSUE THREAD

**Issue by DaanB1** [nekitdev/gd.py#151]
Whenever I try to 'import gd', I get ModuleNotFoundError: No module named 'async_extensions.collect'.
I installed gdpy using !pip install gd.py.
How should I fix this?

**Comment by nekitdev** [comment]
This issue has been recently fixed in e5b95a1b9ad8042fbb7f8c87e42a4f1f0b1cbc97. Try installing the library from source.
