### ISSUE TITLE
Enums?

### ISSUE THREAD

**Issue by stadust** [nekitdev/gd.py#24]
https://github.com/NeKitDS/gd.py/blob/949a61746dba25e46dd3550acbcce683b4ff8c4e/gd/utils/crypto/coders.py#L170

saw you using this on discord, seems like a place an enum would be fancy to use I think?

**Comment by nekitdev** [comment]
Probably, though it's been as strings since the very beginning and it won't really improve anything imo 🤔

**Comment by stadust** [comment]
You'd get the static analyser yelling at you instead of random KeyErrors at runtime if you misspell something :P

**Comment by nekitdev** [comment]
Closing this because I don't really see a point in having enums there.
