### ISSUE TITLE
Question: How to listen for new level rated (any level)

### ISSUE THREAD

**Issue by ghost** [nekitdev/gd.py#29]
Im really confused on how to use the available listeners from this module. I wanna do something if a level gets rated like printing the information about it or storing into a variable. Can someone help me please.

**Comment by DenoXen** [comment]
interesting question..

**Comment by nekitdev** [comment]
First of all, listener's stable API is available only in development version as of now.
You can install it via
```sh
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
```
I thought I described events and listeners fine in the [docs](https://gdpy.readthedocs.io/en/latest/events.html)
Anyways, here is a quick example of doing something when a level gets rated:
```python
import gd

client = gd.Client()  # create our client
client.listen_for("rate")  # create level rate listener

@client.event
async def on_level_rated(level: gd.Level) -> None:
    print(f"{level.name} was rated! ID: {level.id}.")

gd.events.run()  # blocks the thread until stopped
```

**Comment by ghost** [comment]
Thanks, that was a fast response.

**Comment by nekitdev** [comment]
No problem, have fun! :)
