### ISSUE TITLE
Module 'gd' has no 'memory' member

### ISSUE THREAD

**Issue by CattoDev** [nekitdev/gd.py#30]
I was trying to run some example code from the repository, but it seems like gd doesn't contain the "memory" member? Please tell me how to fix this, I'm not that new to python but I still don't know how to fix this issue.

Also "Module 'gd.api' has no 'LevelType' member"

![image](https://user-images.githubusercontent.com/57293929/91072425-c9b79f00-e639-11ea-945e-a79ba99f9981.png)

**Comment by nekitdev** [comment]
Hello! This is due to `gd.memory` being a part of unstable API, which has not yet been released to PyPI.
You can install latest development version via:
```sh
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
```
I am currently working on the rewrite that should stabilize everything. Expect `1.0.0` release on PyPI in foreseeable future.

**Comment by CattoDev** [comment]
Ok I have installed it, but now im getting this error :/

![image](https://user-images.githubusercontent.com/57293929/91074028-464b7d00-e63c-11ea-8ee1-26407dd05b4f.png)

**Comment by nekitdev** [comment]
Interesting. PyLint does not seem to understand what happens under the hood. Memory is an empty class that returns other dedicated classes, like WindowsMemory. Your linter thinks there are no such members, while in fact they are there.

**Comment by CattoDev** [comment]
Oh so that was the problem... Well anyways turns out it works, thanks a lot!
