### ISSUE TITLE
Bad examples

### ISSUE THREAD

**Issue by IvanRoTzEr** [nekitdev/gd.py#31]
When you try to run the example from the memory folder or api, you get an error that says "the GD module does not have the memory attribute".

**Comment by ghost** [comment]
You need the development version of gd.py for this, run `
python -m pip install --upgrade https://github.com/NeKitDS/gd.py/archive/master.zip
`

**Comment by nekitdev** [comment]
We are getting closer to finishing huge rewrite and update; `1.0.0rc1` will be the latest version before stable `1.0.0` release. Of course, a lot of unit tests and documentation improvements are required, but we are getting there.
