### ISSUE TITLE
X position checking not working

### ISSUE THREAD

**Issue by qaiik** [nekitdev/gd.py#37]
I am making an ai. 

The desired result is that when I die in gd, the program saves that place and when I get to a bit before that place, say "yes", but the `print('yes')` does not run, nor does anything else I put in the if statement.

My code is:
```
import math
import time
import gd
import jump

    
Math = math
player = gd.memory.get_memory()
listp = []

while 1:
    if player.is_dead():
        listp.append(Math.floor(player.x_pos))
    try:
        if Math.floor(player.x_pos) + 4 in listp:
            print('yes')
    except:
        pass
    
```

**Comment by Floperatok** [comment]
I've basically the same issue. 
It says "Unresolved attribute reference 'is_dead' for class 'MemoryType'".

My code:
```
import gd

client = gd.Client()
memory = gd.memory.get_memory()

while 1:
    if memory.is_dead():
        print('dead')
```
