### ISSUE TITLE
Найти смещение камеры

### ISSUE THREAD

**Issue by Pixelsuft** [nekitdev/gd.py#38]
Привет, мне нужно найти смещение камеры по Y, чтобы правильно отрисовать игрока по позиции.
Для примера, я сделал небольшой скрипт (для разрешения 640x480 в окне):
```py
import gd.memory
import ctypes
import win32gui, win32ui
a = gd.memory.get_memory()

def winEnumHandler(hwnd, ctx):
    global wnd
    if win32gui.IsWindowVisible(hwnd):
        wnd_text = win32gui.GetWindowText(hwnd)
        if wnd_text == 'Geometry Dash' or wnd_text == 'Geometry Dash Local Multiplayer':
            wnd = hwnd

win32gui.EnumWindows(winEnumHandler, None)

b=(0, 0)

a.player_lock_jump_rotation()

dc = win32gui.GetDC(0)
dcObj = win32ui.CreateDCFromHandle(dc)

rect = win32gui.GetWindowRect(wnd)
wx = rect[0]
wy = rect[1]
ww = rect[2] - wx
wh = rect[3] - wy

px = 8
py = 35

while True:
    ctypes.windll.kernel32.SetConsoleTitleW(f'{a.level_length}, {wx}, {wy}, {ww}, {wh}')
    if not b[0] == a.x_pos or not b[1] == a.y_pos:
        b = (a.x_pos, a.y_pos)
        print(b)
        x = int(b[0] * 0.001) + 200
        y = a.resolution[1] - int(b[1])
        dcObj.Rectangle((wx - px + x, wy - py + y, wx - px + x+40, wy - py + y+40))
```
Он работает почти нормально:
![image1](https://user-images.githubusercontent.com/68371847/122567663-1827a580-d073-11eb-9e22-627a7d5ec2d5.png)
Но когда камера уходит вверх:
![image2](https://user-images.githubusercontent.com/68371847/122568065-92582a00-d073-11eb-85dc-13f5028e079a.png)
Есть ли способ найти значение, на которое сместилась камера, или просто какую-то закономерность?

(Я нуб в ГД)

**Comment by nekitdev** [comment]
The question itself is not trivial. What's more is that it does not belong here, not to mention the fact that English is the only language of this repository. Closing this issue.

**Comment by Pixelsuft** [comment]
I found offsets!
```py
import gd
mem = gd.memory.get_memory()
mem.read_float32(0x3222D0, 0x164, 0x48C) #  camera X
mem.read_float32(0x3222D0, 0x164, 0x490) #  camera Y
```
