### ISSUE TITLE
'Song' Has no attribute 'artist'

### ISSUE THREAD

**Issue by IronDemiGod** [nekitdev/gd.py#44]
`import asyncio

import gd

SONG_ID = 1081309
SONG = "{} by {} (ID: {}, size: {} MB)"

async def main() -> None:
    client = gd.Client()
    song = await client.get_song(SONG_ID)
    print(SONG.format(song.name, song.artist.name, song.id, song.size))

asyncio.run(main())`

**Comment by nekitdev** [comment]
The current API is not in sync with the latest PyPI release.
If you wish to try the new version, consider installing it directly via:
```console
$ python -m pip install https://github.com/nekitdev/gd.py/archive/main.zip
```
