### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Necrosis000** [nekitdev/gd.py#45]
What library gd.py use to get requests from the gd server?

Is it requests, aiohttp, or something else?

**Comment by solstacoded** [comment]
aiohttp https://github.com/nekitdev/gd.py/blob/main/gd/http.py

**Comment by nekitdev** [comment]
Thanks for replying, @sSolsta. Closing this issue as completed.

**Comment by solstacoded** [comment]
did u forget to close it

**Comment by nekitdev** [comment]
Looks like I did, haha :)
