### ISSUE TITLE
AttributeError: module 'gd' has no attribute 'memory'

### ISSUE THREAD

**Issue by NetanelGuber** [nekitdev/gd.py#47]
I get this error when trying to run my file
![image](https://user-images.githubusercontent.com/83191711/220160207-56037dfd-9760-407e-ab09-bf830be071e9.png)

I already looked at the other problems that were posted and they did not help me

**Comment by NetanelGuber** [comment]
nvm i figured it out
how do i close this issue?

**Comment by Weebifying** [comment]
how did you manage to fix the issue? please enlighten me :)

**Comment by THESHARK9001** [comment]
> nvm i figured it out how do i close this issue?

How did you fix this?

**Comment by NetanelGuber** [comment]
it was so long ago i don't remember, sorry

**Comment by THESHARK9001** [comment]
> it was so long ago i don't remember, sorry

could you try to remember? or send me the code that works?

**Comment by NetanelGuber** [comment]
i already deleted it since i didnt need it anymore
