### ISSUE TITLE
`use_custom_song` doesn't work

### ISSUE THREAD

**Issue by ToasterCoder44** [nekitdev/gd.py#62]
Have a look at this code:

```py
client = gd.Client()

levels = await client.search_levels(
    filters = gd.Filters(
        song_id = 1,
        use_custom_song = True
    )
)

print(levels)
```

Documentation suggested that `use_custom_song` is a filter option to treat song id as a custom song id, but result shows levels with *"Stereo Madness"* song instead of those with *"Chilled 1"* song (song with ID equal 1).

gd.py version: 0.11.0

**Comment by nekitdev** [comment]
Hey! This has been fixed in `gd.py v1.0.0` release. Here's an example that should work:

```python
import gd

client = gd.Client()

async def main() -> None:
    levels = await client.search_levels(filters=gd.Filters.with_song(song_id=1, custom=True))

    print(levels)

client.run(main())
```

**Comment by nekitdev** [comment]
Closing this as `v1` fixed the issue.
