### ISSUE TITLE
Allow private server usage in Client.

### ISSUE THREAD

**Issue by magmaus3** [nekitdev/gd.py#66]
It looks like there aren't many ways to set a custom request URL (without modifying the library itself), which could help with tools targeting private GD servers.

**Comment by nekitdev** [comment]
You can use the `http.change(url=PRIVATE_SERVER_URL)` context manager for that.

```python
client = gd.Client()

with client.http.change(url=PRIVATE_SERVER_URL):
    daily = await client.get_daily()
```

**Comment by magmaus3** [comment]
Thanks, it worked.
