### ISSUE TITLE
AttributeError: module 'gd.memory' has no attribute 'get_memory'

### ISSUE THREAD

**Issue by huker667** [nekitdev/gd.py#81]
Code from documentation https://gdpy.readthedocs.io/en/latest/memory.html.

**Comment by THESHARK9001** [comment]
Did you figure this out?

**Comment by huker667** [comment]
> Did you figure this out?

No

**Comment by skylarc2006** [comment]
> Code from documentation https://gdpy.readthedocs.io/en/latest/memory.html.

So he ended up recently making a change but accidentally placed a comma at the last module, messing up that entire portion.
![image](https://github.com/nekitdev/gd.py/assets/137527531/e6a8515a-d178-4941-a27e-7ba70329603b)
For now, you'll just have to install specifically the last version that worked properly, which you can do by uninstalling the current version of gd.py and then using
```pip install git+https://github.com/nekitdev/gd.py.git@b1c954ba69ba6156e9f4ddc2833befdfdf433d85```

**Comment by huker667** [comment]
Thanks

**Comment by THESHARK9001** [comment]
> > Code from documentation https://gdpy.readthedocs.io/en/latest/memory.html.
> 
> So he ended up recently making a change but accidentally placed a comma at the last module, messing up that entire portion. ![image](https://user-images.githubusercontent.com/137527531/263589938-e6a8515a-d178-4941-a27e-7ba70329603b.png) For now, you'll just have to install specifically the last version that worked properly, which you can do by uninstalling the current version of gd.py and then using `pip install git+https://github.com/nekitdev/gd.py.git@b1c954ba69ba6156e9f4ddc2833befdfdf433d85`

I tried this but I still get the error 
![image](https://github.com/nekitdev/gd.py/assets/76677889/60e94ad2-dbc0-4007-9203-b87daa0a23fd)
