### ISSUE TITLE
Add fastapi and lxml requirements when installing gd.py using pip

### ISSUE THREAD

**Issue by AbdiHaryadi** [nekitdev/gd.py#82]
I am using Python 3.10.5. When I have installed gd.py using this command:
```
pip install gd.py
```

I found that I need to install `fastapi` when import it, like this:
```
>>> import gd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<PROJECT_PATH>\venv\lib\site-packages\gd\__init__.py", line 11, in <module>
    from gd import (
  File "<PROJECT_PATH>\venv\lib\site-packages\gd\server\__init__.py", line 1, in <module>
    from gd.server.artists import get_artists
  File "<PROJECT_PATH>\venv\lib\site-packages\gd\server\artists.py", line 3, in <module>
    from fastapi import Depends
ModuleNotFoundError: No module named 'fastapi'
```

After installing `fastapi`, I have another error:
```
>>> import gd
failed to import `lxml`; large portion of `newgrounds` functionality is not going to work
```

It would be better if `fastapi` and `lxml` dependencies are installed too after the first command.

**Comment by AwesomeKalin** [comment]
Also happens with poetry

**Comment by nekitdev** [comment]
`gd.server` library has been marked optional, so you don't need it by default anymore. That said, `lxml` is an *extra* dependency. Installing `lxml` will make XML parsing faster, but it's not available in some cases. You can install `gd.py[speed]` to get it. There are also `crypto`, `image` and `server` extras, which are used to decode macOS saves, generate images and run API wrapping server respectfully.

**Comment by nekitdev** [comment]
Closing this issue as the `ImportError` has been fixed and I've explained the optional dependencies here.

**Comment by nekitdev** [comment]
Closing this issue as the `ImportError` has been fixed and I've explained the why `lxml` is optional.
