### ISSUE TITLE
module 'gd.memory' has no attribute 'get_memory'

### ISSUE THREAD

**Issue by CandyIsaChad** [nekitdev/gd.py#85]
I've been getting this issue, I've referred myself to older cases such as #30, and #81, but it still doesn't work.

![image](https://github.com/nekitdev/gd.py/assets/52960740/bcea5a86-baa5-41f6-9933-d280f01f3e1d)

How do I fix this?

**Comment by nekitdev** [comment]
The latest `gd.py` version has many breaking changes. Feel free to hit me up on my [Discord server](https://nekit.dev/discord) or simply by name: `nekitdev`.

**Comment by nekitdev** [comment]
Closing this as stale.
