### ISSUE TITLE
Level.updated_at and Level.created_at reports current time, not the correct time

### ISSUE THREAD

**Issue by AwesomeKalin** [nekitdev/gd.py#86]
Just before getting into the details, I want to say that this is being tested on the 2.2 GDPS, however is still a bug with gd.py as GDBrowser report the real creation time.

When testing ID 7, the creation time is reported as today at the exact second that the level data was downloaded. This is incorrect, as GDBrowser reports that it was created in 2021

**Comment by nekitdev** [comment]
Hello! This is because gd.py expects the "human" format, as that's what GD servers send as of now. I did not add support for GDPS formats because I simply can't account for everything. Would be nice if GDPS'es would send something like ISO 8601 strings.

**Comment by QuasiStellar** [comment]
I can add that `search_levels` reports current time even on the main GD server. Reproduce:
```
client = Client()
levels = client.search_levels(query=23595659)
async for level in levels:
    print(level.created_at)
```

**Comment by nekitdev** [comment]
Closing this as stale. I'm going to add ISO 8601 support just in case, though.
