### ISSUE TITLE
Uncaught exception in decoding

### ISSUE THREAD

**Issue by QuasiStellar** [nekitdev/gd.py#90]
`decode_base64_url_safe` and similar functions throw uncaught decoding exceptions when the data can't be decoded. There is one case when it happens when getting level info: description of the level with id 296.
![image](https://github.com/nekitdev/gd.py/assets/30569097/f8e63420-47ae-485e-86c9-0c121cc0d167)
![image](https://github.com/nekitdev/gd.py/assets/30569097/95587d0a-b393-46f7-8b5a-2c2f2cdb2fb6)
Throwing exceptions is not necessarily wrong by itself, but these functions are used inside the library in methods (`search_levels` for example) that should not throw decoding exceptions when it can be easily avoided by ignoring the unknown bytes.

**Comment by nekitdev** [comment]
Point is, ignoring unknown bytes gives garbage to the programmers using the library (and consequently to their projects). I think we need to figure out the best way to handle encoding/decoding issues before applying changes.

**Comment by QuasiStellar** [comment]
> gives garbage to the programmers

Isn't it better than not giving anything and crashing with an error instead?

**Comment by nekitdev** [comment]
I said we need to find the *best* way — the proposed solution is merely *better*.

**Comment by QuasiStellar** [comment]
Well, I wasted multiple hours investigating this crash and then rerunning the code that depends on it. None of this would happen if the error-handling strategy was set to "replace" or "ignore" (which GD itself is using) from the start. The problem affects 1 very old level out of 38 000 rated ones and I really don't care if its description contains � instead of a non-breaking space that was supposed to be there for whatever reason. I do care when the libraries I use break down for such minor reasons though.

**Comment by QuasiStellar** [comment]
In general I think that methods such as `search_levels` should never throw if they can get at least _some_ valid info. If something is not right (such as in this case), a warning can be printed.

**Comment by nekitdev** [comment]
You can now handle this via setting `GD_ENCODING_ERRORS` environment variable.
